=== gabriella1696/MPJYO8xmlGyak/MPJYO8_1006/nevjegykartya.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="nevjegykartya">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nev"/>
        <xs:element ref="ceg"/>
        <xs:element ref="beosztas"/>
        <xs:element ref="telefonszam"/>
        <xs:element ref="email"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ceg">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cim"/>
        <xs:element ref="nev"/>
        <xs:element ref="telefonszam"/>
        <xs:element ref="weblap"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="cim">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="iranyitoszam"/>
        <xs:element ref="varos"/>
        <xs:element ref="utca"/>
        <xs:element ref="hazszam"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="iranyitoszam" type="xs:string"/>
  <xs:element name="varos" type="xs:string"/>
  <xs:element name="utca" type="xs:string"/>
  <xs:element name="hazszam" type="xs:integer"/>
  <xs:element name="weblap" type="xs:string"/>
  <xs:element name="beosztas" type="xs:string"/>
  <xs:element name="email" type="xs:string"/>
  <xs:element name="nev" type="xs:string"/>
  <xs:element name="telefonszam">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="korzet" use="required" type="xs:integer"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gabriella1696/MPJYO8xmlGyak/MPJYO8_1006/nevjegykartya.xml
<?xml version="1.0" encoding="UTF-8"?>

<nevjegykartya id="0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/Gabriella/Desktop/egyetem/xml/MPJYO8_1006/nevjegykartya.xsd">
    <nev>
        Hz Gabriella
    </nev>
    <ceg>
        <cim>
            <iranyitoszam>
                3980
            </iranyitoszam>
            <varos>
                Satoraljaujhely
            </varos>
            <utca>
                Karolyi
            </utca>
            <hazszam> 7 </hazszam>

        </cim>
        <nev>
            Sajat Menp Ceg Kft.
        </nev>
        <telefonszam korzet="36"> 123456 </telefonszam>
        <weblap>
            hipermenciweblap.hu
        </weblap>
    </ceg>
    <beosztas>
        Assistant to the Boss's Cat
    </beosztas>
    <telefonszam korzet="36"> 123456 </telefonszam>
    <email>
        gabriella@hipermenciceg.hu
    </email>
</nevjegykartya>
